# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Ahmed/Documents/ece385/chess_ip_repo/hdmi_piece_controller_1_0/src/bToPlay_rom/bToPlay_rom.xci
# IP: The module: 'bToPlay_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Ahmed/Documents/ece385/chess_ip_repo/hdmi_piece_controller_1_0/src/bToPlay_rom/bToPlay_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bToPlay_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess_ip_repo/hdmi_piece_controller_1_0/src/bToPlay_rom/bToPlay_rom.xci
# IP: The module: 'bToPlay_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Ahmed/Documents/ece385/chess_ip_repo/hdmi_piece_controller_1_0/src/bToPlay_rom/bToPlay_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bToPlay_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
