# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Ahmed/Documents/ece385/chess/chess.srcs/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/mb_usb_hdmi_piece_controller_0_0.xci
# IP: The module: 'mb_usb_hdmi_piece_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wToPlay_rom/wToPlay_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wToPlay_rom || ORIG_REF_NAME==wToPlay_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bToPlay_rom/bToPlay_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bToPlay_rom || ORIG_REF_NAME==bToPlay_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wCheckmate_rom/wCheckmate_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wCheckmate_rom || ORIG_REF_NAME==wCheckmate_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bCheckmate_rom/bCheckmate_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bCheckmate_rom || ORIG_REF_NAME==bCheckmate_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/draw_rom/draw_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==draw_rom || ORIG_REF_NAME==draw_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bPromote_rom/bPromote_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bPromote_rom || ORIG_REF_NAME==bPromote_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wPromote_rom/wPromote_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wPromote_rom || ORIG_REF_NAME==wPromote_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bB_rom/bB_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bB_rom || ORIG_REF_NAME==bB_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bN_rom/bN_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bN_rom || ORIG_REF_NAME==bN_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bR_rom/bR_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bR_rom || ORIG_REF_NAME==bR_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bQ_rom/bQ_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bQ_rom || ORIG_REF_NAME==bQ_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bP_rom/bP_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bP_rom || ORIG_REF_NAME==bP_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wB_rom/wB_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wB_rom || ORIG_REF_NAME==wB_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wN_rom/wN_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wN_rom || ORIG_REF_NAME==wN_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wR_rom/wR_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wR_rom || ORIG_REF_NAME==wR_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wQ_rom/wQ_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wQ_rom || ORIG_REF_NAME==wQ_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wP_rom/wP_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wP_rom || ORIG_REF_NAME==wP_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bK_rom/bK_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bK_rom || ORIG_REF_NAME==bK_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wK_rom/wK_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wK_rom || ORIG_REF_NAME==wK_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/board_rom/board_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==board_rom || ORIG_REF_NAME==board_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/hdmi_tx_0/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wToPlay_rom/wToPlay_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bToPlay_rom/bToPlay_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wCheckmate_rom/wCheckmate_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bCheckmate_rom/bCheckmate_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/draw_rom/draw_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bPromote_rom/bPromote_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wPromote_rom/wPromote_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bB_rom/bB_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bN_rom/bN_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bR_rom/bR_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bQ_rom/bQ_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bP_rom/bP_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wB_rom/wB_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wN_rom/wN_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wR_rom/wR_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wQ_rom/wQ_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wP_rom/wP_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bK_rom/bK_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wK_rom/wK_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/board_rom/board_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/clk_wiz_0/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# IP: C:/Users/Ahmed/Documents/ece385/chess/chess.srcs/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/mb_usb_hdmi_piece_controller_0_0.xci
# IP: The module: 'mb_usb_hdmi_piece_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wToPlay_rom/wToPlay_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wToPlay_rom || ORIG_REF_NAME==wToPlay_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bToPlay_rom/bToPlay_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bToPlay_rom || ORIG_REF_NAME==bToPlay_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wCheckmate_rom/wCheckmate_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wCheckmate_rom || ORIG_REF_NAME==wCheckmate_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bCheckmate_rom/bCheckmate_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bCheckmate_rom || ORIG_REF_NAME==bCheckmate_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/draw_rom/draw_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==draw_rom || ORIG_REF_NAME==draw_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bPromote_rom/bPromote_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bPromote_rom || ORIG_REF_NAME==bPromote_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wPromote_rom/wPromote_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wPromote_rom || ORIG_REF_NAME==wPromote_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bB_rom/bB_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bB_rom || ORIG_REF_NAME==bB_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bN_rom/bN_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bN_rom || ORIG_REF_NAME==bN_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bR_rom/bR_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bR_rom || ORIG_REF_NAME==bR_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bQ_rom/bQ_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bQ_rom || ORIG_REF_NAME==bQ_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bP_rom/bP_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bP_rom || ORIG_REF_NAME==bP_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wB_rom/wB_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wB_rom || ORIG_REF_NAME==wB_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wN_rom/wN_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wN_rom || ORIG_REF_NAME==wN_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wR_rom/wR_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wR_rom || ORIG_REF_NAME==wR_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wQ_rom/wQ_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wQ_rom || ORIG_REF_NAME==wQ_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wP_rom/wP_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wP_rom || ORIG_REF_NAME==wP_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bK_rom/bK_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bK_rom || ORIG_REF_NAME==bK_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wK_rom/wK_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wK_rom || ORIG_REF_NAME==wK_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/board_rom/board_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==board_rom || ORIG_REF_NAME==board_rom} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/hdmi_tx_0/hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wToPlay_rom/wToPlay_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bToPlay_rom/bToPlay_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wCheckmate_rom/wCheckmate_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bCheckmate_rom/bCheckmate_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/draw_rom/draw_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bPromote_rom/bPromote_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wPromote_rom/wPromote_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bB_rom/bB_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bN_rom/bN_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bR_rom/bR_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bQ_rom/bQ_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bP_rom/bP_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wB_rom/wB_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wN_rom/wN_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wR_rom/wR_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wQ_rom/wQ_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wP_rom/wP_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/bK_rom/bK_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/wK_rom/wK_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/board_rom/board_rom_ooc.xdc

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Ahmed/Documents/ece385/chess/chess.gen/sources_1/bd/mb_usb/ip/mb_usb_hdmi_piece_controller_0_0_1/src/clk_wiz_0/clk_wiz_0_ooc.xdc
